### PR TITLE
ci: Move php tests from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by micgro42**
Travis-CI is becoming defacto a paid-only service even for open-source

### CODE REVIEW

**Comment by Klap-in** [comment]
Looks fine for me at first glance. However, I guess @phy25 has more experience with setting up the unit tests, could you have a look as well?

**Comment by Klap-in** [comment]
Proof of the pudding is eating;-) Is there already a plugin with this?

**Comment by micgro42** [comment]
I haven't created one with this new template yet, but you can see it in action at https://github.com/micgro42/dokuwiki-plugin-structsection/pull/18

(I think I would want to add the PHP Quality workflow here as well, but maybe only after the next phpmd release)

**Review by Klap-in — APPROVED** [review]
This looks good, and your test at the bookcreator repository shows that it works well as well. 

The tests provided in the wizard are still using the old PHPunit test format, so there is yet an update needed before a working test is available to run. At least class and filename need a update.
https://github.com/dokufreaks/dokuwiki-plugin-wizard/blob/master/skel/_test/general.test.skel

**Comment by splitbrain** [comment]
travis.skel should be deleted

As @Klap-in said, the unit tests would need adjustment for phpunit8, but that would also break testing on stable, because the fetchphpunit script would still use phpunit7 there. I'm not sure what the best approach is.

**Comment by micgro42** [comment]
I dropped the travis.skel.

Could you explain to me why the `general.test.skel` needs adjustment? Testing the `general.test.php` file on other plugins works just fine for me on PHP 8 with splitbrain/dokuwiki#3412. Am I missing something?

That being said, I'm actually happy to rename it to `GeneralTest.skel` and the class to `GeneralTest` as I like it much better if file and class names match and both follow conventions. I just fail to see the connection to PHP8 or PHPUnit 8.

**Comment by micgro42** [comment]
That being said, if we get both  splitbrain/dokuwiki#3412 and subsequently splitbrain/dokuwiki#3404 merged, then I could look into adding PHP 8 to the matrix here and skipping it on stable.

What do you think?

**Comment by splitbrain** [comment]
Oh, you're right. The test doesn't use any inherited methods so we don't need to adjust for the return type hints. I'm merging this. +1 to the PHP8 testing

**Comment by Klap-in** [comment]
hmmm, I realize that I did run the unit tests for the bookcreator plugin via IDEA Intellij.
So in IDEA Intellij the unit test 'general.test.php' was not recognized. (not sure if that is due to my (miss?)configuration of IDEA.

**Comment by micgro42** [comment]
I'd be very open to giving the general.test.php a once-over. Currently, it fails if there are no config files at all.

But maybe I'll do that in a PR on its own? I'm also thinking about adding a test that checks the language files similar (but a bit smarter) to DokuWiki's [_test/tests/general/general_languagelint.test.php](https://github.com/splitbrain/dokuwiki/blob/master/_test/tests/general/general_languagelint.test.php)

**Comment by splitbrain** [comment]
I merged this and updated the website. Separate PR for improved tests welcome.

I guess it would also make sense to have certain default plugin tests in the DokuWiki core that will automatically executed through the dokuwiki-travis script. No sense in copying them to every plugin. The general test is more meant as an example for developer than a "real" test. The language tests could be one of those central tests.

**Pull request merged**
